# Site settings
title: tech blog
email: 
description: "Software Engineer"
baseurl: ""
url: "http://mofeilu.github.io"

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
